-- CreateEnum
CREATE TYPE "EmployeeCount" AS ENUM ('ONE_TO_TEN', 'ELEVEN_TO_FIFTY', 'FIFTY_ONE_TO_TWO_HUNDRED', 'TWO_HUNDRED_AND_ONE_TO_FIVE_HUNDRED', 'FIVE_HUNDRED_AND_ONE_TO_ONE_THOUSAND', 'ONE_THOUSAND_AND_ONE_TO_FIVE_THOUSAND', 'FIVE_THOUSAND_AND_ONE_TO_TEN_THOUSAND', 'TEN_THOUSAND_AND_ONE_PLUS');

-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "employeeCount" "EmployeeCount";
