import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from "@/providers/SessionProvider";
import MainHeader from "@/components/MainHeader";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <NextAuthSessionProvider>
      <MainHeader />

      <div className={"max-w-[64rem] mx-auto mt-14"}>
        {children}
      </div>
    </NextAuthSessionProvider>
    </body>
    </html>
  )
}